# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 AS builder

WORKDIR /go/src/github.com/stolostron/node_exporter
COPY . .

RUN cd promu && go build -mod=mod -o /cachi2/output/deps/gomod/bin/promu

RUN go mod vendor && /cachi2/output/deps/gomod/bin/promu -c ".promu.prow.yml" build -v --prefix /go/src/github.com/stolostron/node_exporter

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest 

COPY --from=builder /go/src/github.com/stolostron/node_exporter/node_exporter /bin/node_exporter

EXPOSE      9100
USER        nobody
ENTRYPOINT  [ "/bin/node_exporter" ]

LABEL com.redhat.component="node-exporter" \
  name="node-exporter" \
  summary="node-exporter" \
  io.openshift.expose-services="" \
  io.openshift.tags="data,images" \
  io.k8s.display-name="node-exporter" \
  maintainer="" \
  description="node-exporter" \
  io.k8s.description="node-exporter"
