FROM registry.ci.openshift.org/stolostron/builder:go1.26-linux AS builder

WORKDIR /go/src/github.com/stolostron/node_exporter
COPY . .
RUN make -f Makefile.prow build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
LABEL io.prometheus.image.variant="prow"

COPY --from=builder /go/src/github.com/stolostron/node_exporter/node_exporter /bin/node_exporter
 
RUN microdnf update -y && microdnf install -y virt-what && microdnf clean all && rm -rf /var/cache/*

EXPOSE      9100
USER        1001
ENTRYPOINT  [ "/bin/node_exporter" ]
