FROM registry.ci.openshift.org/stolostron/builder:go1.18-linux AS builder

WORKDIR /go/src/github.com/stolostron/node_exporter
COPY . .
RUN make build

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest 

COPY --from=builder /go/src/github.com/stolostron/node_exporter/node_exporter /bin/node_exporter
 
RUN microdnf update -y && microdnf install -y virt-what && microdnf clean all && rm -rf /var/cache/*

EXPOSE      9100
USER        nobody
ENTRYPOINT  [ "/bin/node_exporter" ]
